// Mocks generated by Mockito 5.4.6 from annotations
// in home/test/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:ui' as _i7;

import 'package:core_module/core_module.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:report/src/controllers/report_controller.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReportController].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportController extends _i1.Mock implements _i2.ReportController {
  MockReportController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.ReportModel> get reports => (super.noSuchMethod(
        Invocation.getter(#reports),
        returnValue: <_i3.ReportModel>[],
      ) as List<_i3.ReportModel>);

  @override
  List<_i3.ReportModel> get myReports => (super.noSuchMethod(
        Invocation.getter(#myReports),
        returnValue: <_i3.ReportModel>[],
      ) as List<_i3.ReportModel>);

  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get lastOperationFailed => (super.noSuchMethod(
        Invocation.getter(#lastOperationFailed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clearData() => super.noSuchMethod(
        Invocation.method(
          #clearData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearMessage() => super.noSuchMethod(
        Invocation.method(
          #clearMessage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> getReports() => (super.noSuchMethod(
        Invocation.method(
          #getReports,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> getMyReports(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getMyReports,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> finalizeReport({
    required Map<String, dynamic>? reportData,
    _i6.File? imageFile,
    String? existingId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalizeReport,
          [],
          {
            #reportData: reportData,
            #imageFile: imageFile,
            #existingId: existingId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveAsDraft({
    required Map<String, dynamic>? reportData,
    String? localImagePath,
    String? existingId,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAsDraft,
          [],
          {
            #reportData: reportData,
            #localImagePath: localImagePath,
            #existingId: existingId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refreshFromCache({String? userId}) => (super.noSuchMethod(
        Invocation.method(
          #refreshFromCache,
          [],
          {#userId: userId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteReport(
    String? id,
    String? status, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReport,
          [
            id,
            status,
          ],
          {#userId: userId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
