// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYLajuMVA3Re37GBK0kRDfB4zR-Sr5V0',
    appId: '1:478925877632:web:ad3880dc50c6c7c1c35165',
    messagingSenderId: '478925877632',
    projectId: 'lostandfoundimage',
    authDomain: 'lostandfoundimage.firebaseapp.com',
    storageBucket: 'lostandfoundimage.firebasestorage.app',
    measurementId: 'G-SJSXEK9TRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ5S4sZvHcTqTLhojk72KhvzzNcvxrgjY',
    appId: '1:478925877632:android:ff01489060ed3efec35165',
    messagingSenderId: '478925877632',
    projectId: 'lostandfoundimage',
    storageBucket: 'lostandfoundimage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtg8JMYS8L1Tli7V9yEx7X86hftdsVWO0',
    appId: '1:478925877632:ios:b3725cf186565f0bc35165',
    messagingSenderId: '478925877632',
    projectId: 'lostandfoundimage',
    storageBucket: 'lostandfoundimage.firebasestorage.app',
    iosBundleId: 'id.polban.kelompok8.cett.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtg8JMYS8L1Tli7V9yEx7X86hftdsVWO0',
    appId: '1:478925877632:ios:b3725cf186565f0bc35165',
    messagingSenderId: '478925877632',
    projectId: 'lostandfoundimage',
    storageBucket: 'lostandfoundimage.firebasestorage.app',
    iosBundleId: 'id.polban.kelompok8.cett.mainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLYLajuMVA3Re37GBK0kRDfB4zR-Sr5V0',
    appId: '1:478925877632:web:bbd0998313258701c35165',
    messagingSenderId: '478925877632',
    projectId: 'lostandfoundimage',
    authDomain: 'lostandfoundimage.firebaseapp.com',
    storageBucket: 'lostandfoundimage.firebasestorage.app',
    measurementId: 'G-R1KEC3MEKL',
  );
}
